name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Clean _site directory
        run: rm -rf _site

      - name: List directory before build
        run: |
          echo "Directory structure before build:"
          ls -la
          echo "_site directory before build:"
          ls -la _site || echo "_site directory does not exist"

      - name: Build
        run: pnpm build

      - name: List generated content
        run: |
          echo "Directory structure after build:"
          ls -la
          echo "_site directory contents:"
          ls -la _site
          echo "_site directory structure:"
          find _site -type f -o -type d | sort

      - name: Create tar.gz archive
        run: |
          cd _site
          tar -czf ./site.tar.gz .

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 